### ISSUE TITLE
Error with mountainlab_pytools.mlproc attributes

### ISSUE THREAD

**Issue by moshen80** [flatironinstitute/mountainsort_examples#10]
Hi,
I've been trying to test the mountainsort package but at the first try to run the examples I get error with mountainlab_pytools.mlproc attributes, e.g. when running ms4_jupyter_example , I got the AttributeError: module 'mountainlab_pytools.mlproc' has no attribute 'initPipeline' Error. I checked and all the required packages have been installed as per the instruction.
any help would appreciated.
BR

**Comment by cuckoong** [comment]
I have the same problem. Is this because I am using it on mac?
