### ISSUE TITLE
issue importing mountainsort4_1_0

### ISSUE THREAD

**Issue by elliothsmith** [flatironinstitute/mountainsort_examples#12]
Hello, I'm excited to try this out, but I'm getting a 'No module' error for mountainsort4_1_0 in this example. Is this package deprecated or, more likely, am I missing something? I also tried importing \ml_ms4alg instead, with no luck. Thanks!

**Comment by elliothsmith** [comment]
Sorry, I'm dumb.

**Comment by MyNameIsMoney** [comment]
Hello, I have met the same problem as you. Would you like to tell me how you deal with this problem? Thank you.

**Comment by tjd2002** [comment]
The `mountainsort` metapackages have not been updated recently and are not a supported way to install MountainLab+MountainSort. We’ll be revisiting this soon. 

In the meantime please follow the current install instructions under “installation with conda” dropdown section here: https://github.com/flatironinstitute/mountainsort_examples/blob/master/README.md

**Comment by MyNameIsMoney** [comment]
Thanks for your reply. I have removed the all environment and have  installed them all following the steps of the that website, and there  were no error during I installed the mountainlab or mountainsort. But  now, I couldn't still run this example in jupyter lab. The error means  "No module named 'mountainsort4_1_0'"  "No module named ''" "No module  named 'validate_sorting_results'" No module named 'synthesize_dataset'" .  I  couldn't find this file in my computer, but I found a file name  'mountainsort4_v1', I also found the part 'sort_dataset' in this file.  But the other two module I couldn't have found them before now. And I can run the bash example successfully. I use  the ubuntu18.04. However, my partner use the ubuntu18.04 in virtual machine  didn't meet this problem. I am really confused. Could you give me some  suggestion? Thank you.




------------------ 原始邮件 ------------------
发件人: "Tom Davidson"<notifications@github.com>;
发送时间: 2019年1月21日(星期一) 凌晨5:05
收件人: "flatironinstitute/mountainsort_examples"<mountainsort_examples@noreply.github.com>;
抄送: "453646719"<453646719@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [flatironinstitute/mountainsort_examples] issue importingmountainsort4_1_0 (#12)



The `mountainsort` metapackages have not been updated recently and are not a supported way to install MountainLab+MountainSort. We’ll be revisiting this soon. 
 
 In the meantime please follow the current install instructions under “installation with conda” dropdown section here: https://github.com/flatironinstitute/mountainsort_examples/blob/master/README.md
