### ISSUE TITLE
Jupyter widgets problem

### ISSUE THREAD

**Issue by Alkohost** [flatironinstitute/mountainsort_examples#14]
Hello,
  I installed everything according to the ReadMe and tryed to run the example for Jupyter Lab but faced with this:

Pipeline=mlp.initPipeline()
   Error displaying widget

with Pipeline:
    synthesize_dataset(dsdir,M=4,duration=600,average_snr=8)

 185         #self._job_monitor.widget().clearJobs()
    186 
--> 187         self._status_out=widgets.Output()
    188         display(self._status_out)
    189         self._last_status_string=''

NameError: name 'widgets' is not defined

As I understand is something wrong with setting up widgets, but there was no errors during install.
Why it happens?
Bash example works perfectly.

**Comment by tjd2002** [comment]
This is a known issue, fixed in source. We just need to push the fix to the anaconda package repos. I assume you are running Linux?

We should have the fix up shortly; in the meantime, you should be able to upgrade from my testing repository with:
`conda install -c tjd2002 'mountainlab_pytools=0.7.4'`

**Comment by Alkohost** [comment]
It works now. Thank you.
Yes, I use Ubuntu 18.04.1
Is there an ability to run everything on Windows?

**Comment by tjd2002** [comment]
Nope, but macOS support is possible

**Comment by cuckoong** [comment]
> This is a known issue, fixed in source. We just need to push the fix to the anaconda package repos. I assume you are running Linux?
> 
> We should have the fix up shortly; in the meantime, you should be able to upgrade from my testing repository with:
> `conda install -c tjd2002 'mountainlab_pytools=0.7.4'`

Hi, I tried to install this version of mounainlab_pytools but could not found this package. Is this because of the system I used is not linux?

**Comment by tjd2002** [comment]
Yes, that is correct. I only have the Linux packages built at that
location. Mac support is currently lagging a bit behind Linux, but in
principle we can build for both platforms if there is demand.
