### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by holmescharles** [flatironinstitute/mountainsort_examples#25]
Hi! I have set up mountainsort and ephys-viz as per https://github.com/flatironinstitute/mountainsort_examples. I then made the sample dataset with "synthesize_dataset.sh", but when I try to look at the data with ev-dataset dataset, an error is raised:

```
/data/code/python/miniconda3-chuck/envs/mount2/lib/node_modules/ephys-viz/node_modules/electron/dist/electron: symbol lookup error: /data/code/python/miniconda3-chuck/envs/mount2/lib/node_modules/ephys-viz/node_modules/electron/dist/../../../../../libfontconfig.so.1: undefined symbol: FT_Done_MM_Var
```

Any idea what the issue is?
Thanks

**Comment by ucnsgy** [comment]
libfontconfig.so.1 links to libfontconfig.so.1.12.0 in the mountainlab lib directory 
(in your case this is /data/code/python/miniconda3-chuck/envs/mount2/lib/)

depending on your build/version of linux and libfontconfig, libfontconfig.so.1.12.0 may not be pointing to the correct freetype library

i fixed this for myself by updating libfontconfig, copying the latest version of the libfontconfig.so.1.X.0 file to my mountainlab lib directory, and re-linking libfontconfig.so.1 to it. 

if you are using Ubuntu, this would look something like this
> sudo apt-get install libfontconfig1
> cp /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.10.1 /data/code/python/miniconda3-chuck/envs/mount2/lib/. (your lib directory may be different, and libfontconfig.so.1.10.1 may be different)
> cd /data/code/python/miniconda3-chuck/envs/mount2/lib/
> rm libfontconfig.so.1
> ln -s libfontconfig.so.1.10.1 libfontconfig.so.1 (again, libfontconfig.so.1.10.1 may be different, ie- libfontconfig.so.1.12.1)

hope that helps

**Comment by holmescharles** [comment]
Thanks!

On Mon, Oct 21, 2019 at 3:07 PM ucnsgy <notifications@github.com<mailto:notifications@github.com>> wrote:

libfontconfig.so.1 links to libfontconfig.so.1.12.0 in the mountainlab lib directory
(in your case this is /data/code/python/miniconda3-chuck/envs/mount2/lib/)

depending on your build/version of linux and libfontconfig, libfontconfig.so.1.12.0 may not be pointing to the correct freetype library

i fixed this for myself by updating libfontconfig, copying the latest version of the libfontconfig.so.1.X.0 file to my mountainlab lib directory, and re-linking libfontconfig.so.1 to it.

if you are using Ubuntu, this would look something like this

sudo apt-get install libfontconfig1
cp /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.10.1 /data/code/python/miniconda3-chuck/envs/mount2/lib/. (your lib directory may be different, and libfontconfig.so.1.10.1 may be different)
cd /data/code/python/miniconda3-chuck/envs/mount2/lib/
rm libfontconfig.so.1
ln -s libfontconfig.so.1.10.1 libfontconfig.so.1 (again, libfontconfig.so.1.10.1 may be different, ie- libfontconfig.so.1.12.1)

hope that helps
