### ISSUE TITLE
Sorting detected spikes

### ISSUE THREAD

**Issue by ferchaure** [flatironinstitute/mountainsort_examples#28]
Hi Jeremy,

Do you plan to add support for detected spikes? I know is not the best way to test things, but reading about the algorithm I really want to test things like interpolating before aligning the clips, etc.

**Comment by magland** [comment]
Do you mean... you have spike times already and you want to feed that into mountainsort?

**Comment by ferchaure** [comment]
no, I have just the spikes (without the raw signal), each as a matrix of 50 samples x N channels and I want to feed them into mountainsort

**Comment by magland** [comment]
We don't really support a snippets mode. But you can look at the source code and piece together a solution: https://github.com/magland/ml_ms4alg/blob/master/ml_ms4alg/ms4alg.py

There you can see code for computing the PCA features and calling isosplit.

**Comment by ferchaure** [comment]
Ok, I will

**Comment by ferchaure** [comment]
Hi, again, that was easy to do . But I can't understand why the '*2' on: `compute_principal_components(clips_for_pca.reshape((M_neigh*clip_size,len(times_for_pca))),num_features*2) `

I read the comment: 
> use twice as many features, because of branch method

And I guess that the idea is to first calculate 20 features and then the brach method recalculates the features from only that 20 to reduce calculations. am I right?
Or maybe the idea is to cap the PCA components to use because, otherwise, the brach method could use a non-informative feature?
