### ISSUE TITLE
Error occurred when I ran the 001_ms4_jupyter_example file

### ISSUE THREAD

**Issue by kalfton** [flatironinstitute/mountainsort_examples#4]
Hi, 
I installed newest version of mountainlab in miniconda and I think I have followed every instructions in the readme files. But when I tried to run the first example file "001_ms4_jupyter_example" it throws error in the following cell block, which returned: "Exception: Error running process ms4alg.sort: Process returned with non-zero error code (255)". 
Do anyone knows how to solve it?
Thanks!
![screenshot from 2018-09-09 19-55-18](https://user-images.githubusercontent.com/36215989/45271178-a1453300-b46a-11e8-823f-40b7451ac6bd.png)
![screenshot from 2018-09-09 19-55-38](https://user-images.githubusercontent.com/36215989/45271179-a1453300-b46a-11e8-9752-c025baee414c.png)
![screenshot from 2018-09-09 19-56-46](https://user-images.githubusercontent.com/36215989/45271180-a1453300-b46a-11e8-90eb-ebd44c474c10.png)

**Comment by magland** [comment]
Thanks for the report. You should see an additional error information in the job monitor widget in a previous cell... looks something like this (except with an error for ms4alg.sort):

![image](https://user-images.githubusercontent.com/3679296/45309909-dc8b4480-b4f2-11e8-8f6b-561b165d93d9.png)

But I just improved the error reporting, so if you conda install the latest version of mountainlab_pytools (version 0.6.10 or later), then you will get better error reporting even without having to look back at the previous cell.

Let me know what you see is the error you are getting for that specific processor (ms4alg.sort).

**Comment by kalfton** [comment]
Hi, 
I updated mountainlab_pytools, the reported error seems changed a little bit, but still exist. (Now it is in ms3.isolation_metrics...)
Thanks

![screenshot from 2018-09-10 16-49-32](https://user-images.githubusercontent.com/36215989/45327379-ee81dd00-b51c-11e8-834e-03de96fdefd0.png)
![screenshot from 2018-09-10 16-48-33](https://user-images.githubusercontent.com/36215989/45327384-f2adfa80-b51c-11e8-8d68-2f20f0e519a2.png)
![screenshot from 2018-09-10 16-48-57](https://user-images.githubusercontent.com/36215989/45327386-f5105480-b51c-11e8-8d44-a0394aca30cf.png)

**Comment by magland** [comment]
Could you please expand the ms3.isolation_metrics error (red) and show me what that error is?

**Comment by kalfton** [comment]
I can not expand the exception... It looks like that "Exception: [Click to expand]" is just pure text

**Comment by magland** [comment]
How about the right-arrow to the left of the red "error" string toward the top?

**Comment by kalfton** [comment]
![screenshot from 2018-09-10 17-38-50](https://user-images.githubusercontent.com/36215989/45328190-73222a80-b520-11e8-96e3-542b669ae4d7.png)

**Comment by magland** [comment]
Okay, so it seems you don't have ml_ms3 package installed. Which installation instructions were you following? Conda? If so, it should have included ml_ms3 package on the flatiron channel...

**Comment by kalfton** [comment]
Okay, It works after I installed ml_ms3. Yes, I followed the installation of conda version, I read it again, and found that this package is only mentioned here, and I ignored it when I installed... But anyway, thank you for helping me solving it!
![screenshot from 2018-09-10 17-53-18](https://user-images.githubusercontent.com/36215989/45328729-c8f7d200-b522-11e8-8c4d-811ade6eb6aa.png)

**Comment by magland** [comment]
Okay great! Yeah, I'll clarify that part of the docs.
