### ISSUE TITLE
Different clusters found every time pipeline is run on same data. 

### ISSUE THREAD

**Issue by linamnt** [flatironinstitute/mountainsort_examples#5]
We synthesized data once, and when we ran the pipeline multiple times (clearing the output folder and tmp files just to sure), we always got different clustering results (i.e. numbers) when we looked at firings_uncurated.mda and as a result in the final firings.mda .

**Comment by magland** [comment]
Yes, the algorithm is not deterministic. Re-running gives an idea about stability of the method.

**Comment by linamnt** [comment]
Okay thank you for the information, we were unsure if this was by design or if we had problems with the installation/implementation.
