### ISSUE TITLE
Interpretation of the outputs

### ISSUE THREAD

**Issue by ukky17** [flatironinstitute/mountainsort_examples#8]
Hello, I am very new to MountainSort. I ran the sorting program on my own dataset (in vivo recording using a Neuronexus 32-ch linear probe) following `ms4_jupyter_example.ipynb`, and `firing.mda` was successfully generated. However, I have several questions on the output files since there seem no documents for the interpretation of the outputs (except for https://mountainsort.readthedocs.io/en/latest/first_sort.html ).

1. Does the third row of `firings.mda` indicate the cluster IDs? i.e. if there are 5 kinds of numbers (e.g. {50, 51, 56, 25, 32}), does it mean 5 clusters were identified after curation?
2. How can I get the time course of each identified clusters?

Thank you in advance.

**Comment by magland** [comment]
Thanks for the question. I expanded the docs... see "Accessing and interpreting outputs" in https://github.com/flatironinstitute/mountainsort_examples/blob/master/README.md

Let me know if this answers your questions.

**Comment by ukky17** [comment]
Awesome! Thank you!
